name: testes-unitarios

on: [pull_request, push]

jobs:
 testes-unitarios:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Using Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 21.
    - name: run install, build and test
      run: |
        npm install
        npm run test